"""
Figure generation for LST IEEE paper.
Run this script after training to generate publication-quality figures.

Usage:
    python generate_figures.py              # loads from checkpoint files
    python generate_figures.py --from-run   # uses live variables (in notebook)

Required files (generated by training notebook):
    lst_checkpoint.pkl
    baseline_checkpoint.pkl

Output:
    paper/figures/fig1_architecture.pdf
    paper/figures/fig2_loss_curves.pdf
    paper/figures/fig3_acceptance_rate.pdf
    paper/figures/fig4_step_time_distribution.pdf
    paper/figures/fig5_cost_model.pdf
    paper/figures/fig6_speedup_vs_acceptance.pdf
"""

import pickle
import os
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.gridspec import GridSpec

# IEEE style settings
plt.rcParams.update({
    'font.family': 'serif',
    'font.serif': ['Times New Roman', 'Times', 'DejaVu Serif'],
    'font.size': 9,
    'axes.labelsize': 10,
    'axes.titlesize': 10,
    'legend.fontsize': 8,
    'xtick.labelsize': 8,
    'ytick.labelsize': 8,
    'figure.dpi': 300,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight',
    'savefig.pad_inches': 0.05,
    'lines.linewidth': 1.0,
    'axes.grid': True,
    'grid.alpha': 0.3,
    'grid.linewidth': 0.5,
})

# IEEE column width = 3.5 inches, full width = 7.16 inches
COL_WIDTH = 3.5
FULL_WIDTH = 7.16

OUT_DIR = os.path.join(os.path.dirname(__file__), 'figures')
os.makedirs(OUT_DIR, exist_ok=True)


def load_checkpoints(lst_path='lst_checkpoint.pkl', baseline_path='baseline_checkpoint.pkl'):
    """Load training results from checkpoint files."""
    with open(lst_path, 'rb') as f:
        lst = pickle.load(f)
    with open(baseline_path, 'rb') as f:
        base = pickle.load(f)
    return lst, base


# ====================================================================
#  Figure 1: Architecture Diagram (text-based for IEEE)
# ====================================================================
def fig1_architecture():
    """
    Architecture diagram. Since matplotlib can't do complex diagrams well,
    this generates a structured block diagram.

    For best results, recreate this in TikZ using the LaTeX code below.
    """
    fig, ax = plt.subplots(figsize=(COL_WIDTH, 3.5))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 10)
    ax.axis('off')

    # Boxes
    boxes = [
        (1, 8.5, 3, 1, 'Target Model\n(GPT-2 124M)', '#E3F2FD'),
        (6, 8.5, 3, 1, 'Draft Model\n(3M params)', '#FFF3E0'),
        (3, 6.5, 4, 1, 'Feature Extraction\n(134 dims × 48 layers)', '#E8F5E9'),
        (3, 4.5, 4, 1, 'Low-Rank Decode\n(BMM, rank=8)', '#FFF3E0'),
        (3, 2.5, 4, 1, 'Verify (Eval Forward)\n$\\mathcal{L}_{verify} < \\bar{\\mathcal{L}}(1+\\tau)$?', '#FCE4EC'),
        (0.5, 0.5, 3.5, 1, 'ACCEPT\n(keep update)', '#C8E6C9'),
        (6, 0.5, 3.5, 1, 'REJECT\n(rollback + std step)', '#FFCDD2'),
    ]

    for x, y, w, h, text, color in boxes:
        rect = mpatches.FancyBboxPatch(
            (x, y), w, h, boxstyle='round,pad=0.1',
            facecolor=color, edgecolor='black', linewidth=0.8
        )
        ax.add_patch(rect)
        ax.text(x + w/2, y + h/2, text, ha='center', va='center', fontsize=7, wrap=True)

    # Arrows
    arrows = [
        (2.5, 8.5, 2.5, 7.5),   # Target -> Features
        (7.5, 8.5, 7.5, 7.5),   # Draft -> Features (conceptual)
        (5, 6.5, 5, 5.5),       # Features -> Decode
        (5, 4.5, 5, 3.5),       # Decode -> Verify
        (3.5, 2.5, 2.25, 1.5),  # Verify -> Accept
        (6.5, 2.5, 7.75, 1.5),  # Verify -> Reject
    ]

    for x1, y1, x2, y2 in arrows:
        ax.annotate('', xy=(x2, y2), xytext=(x1, y1),
                    arrowprops=dict(arrowstyle='->', color='black', lw=0.8))

    ax.set_title('Fig. 1: LST Architecture Overview', fontsize=10, fontweight='bold', pad=10)
    fig.savefig(os.path.join(OUT_DIR, 'fig1_architecture.pdf'))
    fig.savefig(os.path.join(OUT_DIR, 'fig1_architecture.png'))
    plt.close(fig)
    print("Generated fig1_architecture")


# ====================================================================
#  Figure 2: Training Loss Curves
# ====================================================================
def fig2_loss_curves(lst, base):
    """Training loss comparison: LST vs Baseline."""
    fig, ax = plt.subplots(figsize=(COL_WIDTH, 2.2))

    window = 50
    losses_lst = np.array(lst['losses'])
    losses_base = np.array(base['baseline_losses'])

    if len(losses_lst) > window:
        smoothed_lst = np.convolve(losses_lst, np.ones(window)/window, mode='valid')
        ax.plot(range(window//2, window//2 + len(smoothed_lst)), smoothed_lst,
                label='LST', color='#1976D2', linewidth=1.2)

    if len(losses_base) > window:
        smoothed_base = np.convolve(losses_base, np.ones(window)/window, mode='valid')
        ax.plot(range(window//2, window//2 + len(smoothed_base)), smoothed_base,
                label='Baseline', color='#D32F2F', linewidth=1.2, linestyle='--')

    ax.set_xlabel('Training Step')
    ax.set_ylabel('Training Loss')
    ax.set_title('(a) Training Loss Comparison')
    ax.legend(loc='upper right', framealpha=0.9)

    # Annotate final losses
    ax.annotate(f'LST: {np.mean(losses_lst[-50:]):.2f}',
                xy=(len(losses_lst)-1, np.mean(losses_lst[-50:])),
                fontsize=7, color='#1976D2')
    ax.annotate(f'Baseline: {np.mean(losses_base[-50:]):.2f}',
                xy=(len(losses_base)-1, np.mean(losses_base[-50:])),
                fontsize=7, color='#D32F2F')

    fig.savefig(os.path.join(OUT_DIR, 'fig2_loss_curves.pdf'))
    fig.savefig(os.path.join(OUT_DIR, 'fig2_loss_curves.png'))
    plt.close(fig)
    print("Generated fig2_loss_curves")


# ====================================================================
#  Figure 3: Acceptance Rate Over Training (THE key plot)
# ====================================================================
def fig3_acceptance_rate(lst):
    """Rolling acceptance rate with break-even line and phase annotations."""
    fig, ax = plt.subplots(figsize=(COL_WIDTH, 2.2))

    accepted_flags = np.array(lst['accepted_flags'])
    warmup_steps = 50

    # Rolling acceptance rate (window=100)
    rolling_window = 100
    if len(accepted_flags) > rolling_window:
        rolling = np.convolve(accepted_flags, np.ones(rolling_window)/rolling_window, mode='valid')
        x_vals = np.arange(warmup_steps + rolling_window//2,
                          warmup_steps + rolling_window//2 + len(rolling))
        ax.plot(x_vals, rolling * 100, color='#388E3C', linewidth=1.2, label='Acceptance rate')

    # Break-even line
    ax.axhline(y=42, color='#D32F2F', linestyle=':', linewidth=0.8, alpha=0.8, label='Break-even (42%)')

    # Phase annotations
    ax.axvspan(0, 50, alpha=0.1, color='gray', label='Warmup')
    ax.axvline(x=50, color='gray', linestyle='--', linewidth=0.5, alpha=0.7)
    ax.axvline(x=400, color='orange', linestyle='--', linewidth=0.5, alpha=0.5)
    ax.axvline(x=1000, color='orange', linestyle='--', linewidth=0.5, alpha=0.5)

    # Phase labels
    ax.text(225, 15, 'Early\n99-100%', ha='center', fontsize=6, color='#388E3C')
    ax.text(700, 15, 'Mid\n97→88%', ha='center', fontsize=6, color='#F57C00')
    ax.text(1500, 15, 'Late\n88→76%', ha='center', fontsize=6, color='#D32F2F')

    ax.set_xlabel('Training Step')
    ax.set_ylabel('Acceptance Rate (%)')
    ax.set_title('(b) Acceptance Rate Trajectory')
    ax.set_ylim(-5, 105)
    ax.set_xlim(0, 2050)
    ax.legend(loc='lower left', fontsize=7, framealpha=0.9)

    fig.savefig(os.path.join(OUT_DIR, 'fig3_acceptance_rate.pdf'))
    fig.savefig(os.path.join(OUT_DIR, 'fig3_acceptance_rate.png'))
    plt.close(fig)
    print("Generated fig3_acceptance_rate")


# ====================================================================
#  Figure 4: Step Time Distribution
# ====================================================================
def fig4_step_time_distribution(lst, base):
    """Histogram of per-step times for LST vs Baseline."""
    fig, ax = plt.subplots(figsize=(COL_WIDTH, 2.2))

    lst_times = np.array(lst['step_times']) * 1000  # to ms
    base_times = np.array(base['baseline_times']) * 1000

    bins = np.linspace(0, max(lst_times.max(), base_times.max()) * 1.05, 60)

    ax.hist(lst_times, bins=bins, alpha=0.6, color='#1976D2', label='LST', density=True)
    ax.hist(base_times, bins=bins, alpha=0.6, color='#D32F2F', label='Baseline', density=True)

    # Vertical lines for means
    ax.axvline(x=np.mean(lst_times), color='#1976D2', linestyle='--', linewidth=0.8)
    ax.axvline(x=np.mean(base_times), color='#D32F2F', linestyle='--', linewidth=0.8)

    ax.text(np.mean(lst_times) + 20, ax.get_ylim()[1] * 0.85,
            f'LST avg: {np.mean(lst_times):.0f}ms', fontsize=7, color='#1976D2')
    ax.text(np.mean(base_times) + 20, ax.get_ylim()[1] * 0.7,
            f'Baseline avg: {np.mean(base_times):.0f}ms', fontsize=7, color='#D32F2F')

    ax.set_xlabel('Step Time (ms)')
    ax.set_ylabel('Density')
    ax.set_title('(c) Step Time Distribution')
    ax.legend(loc='upper right', fontsize=7, framealpha=0.9)

    fig.savefig(os.path.join(OUT_DIR, 'fig4_step_time_distribution.pdf'))
    fig.savefig(os.path.join(OUT_DIR, 'fig4_step_time_distribution.png'))
    plt.close(fig)
    print("Generated fig4_step_time_distribution")


# ====================================================================
#  Figure 5: Cost Model — Standard vs Speculative
# ====================================================================
def fig5_cost_model():
    """Bar chart comparing per-step costs for different step types."""
    fig, ax = plt.subplots(figsize=(COL_WIDTH, 2.2))

    categories = ['Baseline\n(4× fwd+bwd)', 'LST Warmup', 'LST Accepted\n(eval-fwd)', 'LST Rejected\n(rollback+std)']
    values = [1226, 1341, 156, 1400]
    colors = ['#D32F2F', '#FF9800', '#388E3C', '#F44336']

    bars = ax.bar(categories, values, color=colors, edgecolor='black', linewidth=0.5, width=0.6)

    # Value labels
    for bar, val in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 30,
                f'{val}ms', ha='center', va='bottom', fontsize=7, fontweight='bold')

    # Savings annotation
    ax.annotate('87% cheaper', xy=(2, 156), xytext=(2.8, 600),
                fontsize=8, color='#388E3C', fontweight='bold',
                arrowprops=dict(arrowstyle='->', color='#388E3C', lw=1.2))

    ax.set_ylabel('Time per Step (ms)')
    ax.set_title('(d) Per-Step Cost Comparison')
    ax.set_ylim(0, 1700)

    fig.savefig(os.path.join(OUT_DIR, 'fig5_cost_model.pdf'))
    fig.savefig(os.path.join(OUT_DIR, 'fig5_cost_model.png'))
    plt.close(fig)
    print("Generated fig5_cost_model")


# ====================================================================
#  Figure 6: Theoretical Speedup vs Acceptance Rate
# ====================================================================
def fig6_speedup_vs_acceptance():
    """Speedup curve as a function of acceptance rate with measured point."""
    fig, ax = plt.subplots(figsize=(COL_WIDTH, 2.2))

    # Measured values
    C_std = 1226
    C_acc = 156
    C_rej = 1400

    p_range = np.linspace(0, 1, 200)
    speedup = C_std / (p_range * C_acc + (1 - p_range) * C_rej)

    ax.plot(p_range * 100, speedup, color='#1976D2', linewidth=1.2, label='Theoretical speedup')

    # Break-even line
    ax.axhline(y=1.0, color='gray', linestyle='-', linewidth=0.5, alpha=0.5)
    break_even = (C_rej - C_std) / (C_rej - C_acc) * 100
    ax.axvline(x=break_even, color='#D32F2F', linestyle=':', linewidth=0.8, alpha=0.8,
               label=f'Break-even ({break_even:.0f}%)')

    # Measured point
    measured_p = 76.3
    measured_speedup = 2.02
    ax.scatter([measured_p], [measured_speedup], color='#388E3C', s=60, zorder=5,
               edgecolors='black', linewidth=0.8, label=f'Measured (76.3%, 2.02×)')

    # Theoretical at same acceptance
    theoretical_at_76 = C_std / (0.763 * C_acc + 0.237 * C_rej)
    ax.scatter([measured_p], [theoretical_at_76], color='#FF9800', s=40, zorder=5,
               marker='^', edgecolors='black', linewidth=0.8,
               label=f'Theory at 76.3% ({theoretical_at_76:.2f}×)')

    ax.set_xlabel('Acceptance Rate (%)')
    ax.set_ylabel('Wall-Clock Speedup (×)')
    ax.set_title('(e) Speedup vs Acceptance Rate')
    ax.set_xlim(0, 100)
    ax.set_ylim(0.5, max(speedup) * 1.05)
    ax.legend(loc='upper left', fontsize=6.5, framealpha=0.9)

    fig.savefig(os.path.join(OUT_DIR, 'fig6_speedup_vs_acceptance.pdf'))
    fig.savefig(os.path.join(OUT_DIR, 'fig6_speedup_vs_acceptance.png'))
    plt.close(fig)
    print("Generated fig6_speedup_vs_acceptance")


# ====================================================================
#  Combined Figure (for paper — 2×3 grid)
# ====================================================================
def fig_combined(lst, base):
    """Generate a single combined 2×3 figure for the paper."""
    fig = plt.figure(figsize=(FULL_WIDTH, 4.5))
    gs = GridSpec(2, 3, figure=fig, hspace=0.45, wspace=0.35)

    # ---- (a) Loss Curves ----
    ax = fig.add_subplot(gs[0, 0])
    window = 50
    losses_lst = np.array(lst['losses'])
    losses_base = np.array(base['baseline_losses'])
    if len(losses_lst) > window:
        s = np.convolve(losses_lst, np.ones(window)/window, mode='valid')
        ax.plot(range(window//2, window//2+len(s)), s, label='LST', color='#1976D2', lw=1.0)
    if len(losses_base) > window:
        s = np.convolve(losses_base, np.ones(window)/window, mode='valid')
        ax.plot(range(window//2, window//2+len(s)), s, label='Baseline', color='#D32F2F', lw=1.0, ls='--')
    ax.set_xlabel('Step')
    ax.set_ylabel('Loss')
    ax.set_title('(a) Training Loss')
    ax.legend(fontsize=6)

    # ---- (b) Acceptance Rate ----
    ax = fig.add_subplot(gs[0, 1])
    flags = np.array(lst['accepted_flags'])
    rw = 100
    if len(flags) > rw:
        r = np.convolve(flags, np.ones(rw)/rw, mode='valid')
        x = np.arange(50 + rw//2, 50 + rw//2 + len(r))
        ax.plot(x, r*100, color='#388E3C', lw=1.0)
    ax.axhline(y=42, color='#D32F2F', ls=':', lw=0.8, label='Break-even')
    ax.set_xlabel('Step')
    ax.set_ylabel('Accept Rate (%)')
    ax.set_title('(b) Acceptance Rate')
    ax.set_ylim(-5, 105)
    ax.legend(fontsize=6)

    # ---- (c) Step Time Distribution ----
    ax = fig.add_subplot(gs[0, 2])
    lt = np.array(lst['step_times'])*1000
    bt = np.array(base['baseline_times'])*1000
    bins = np.linspace(0, max(lt.max(), bt.max())*1.05, 50)
    ax.hist(lt, bins=bins, alpha=0.6, color='#1976D2', label='LST', density=True)
    ax.hist(bt, bins=bins, alpha=0.6, color='#D32F2F', label='Baseline', density=True)
    ax.set_xlabel('ms/step')
    ax.set_ylabel('Density')
    ax.set_title('(c) Step Time Distribution')
    ax.legend(fontsize=6)

    # ---- (d) Cost Bar Chart ----
    ax = fig.add_subplot(gs[1, 0])
    cats = ['Baseline', 'Warmup', 'Accepted', 'Rejected']
    vals = [1226, 1341, 156, 1400]
    cols = ['#D32F2F', '#FF9800', '#388E3C', '#F44336']
    bars = ax.bar(cats, vals, color=cols, edgecolor='black', lw=0.5, width=0.55)
    for b, v in zip(bars, vals):
        ax.text(b.get_x()+b.get_width()/2, b.get_height()+20, f'{v}', ha='center', fontsize=6)
    ax.set_ylabel('ms/step')
    ax.set_title('(d) Per-Step Cost')

    # ---- (e) Speedup vs Acceptance ----
    ax = fig.add_subplot(gs[1, 1])
    C_s, C_a, C_r = 1226, 156, 1400
    p = np.linspace(0.01, 1, 200)
    sp = C_s / (p*C_a + (1-p)*C_r)
    ax.plot(p*100, sp, color='#1976D2', lw=1.0)
    ax.axhline(y=1, color='gray', lw=0.5)
    be = (C_r-C_s)/(C_r-C_a)*100
    ax.axvline(x=be, color='#D32F2F', ls=':', lw=0.8)
    ax.scatter([76.3], [2.02], color='#388E3C', s=40, zorder=5, edgecolors='k', lw=0.5)
    ax.text(76.3+2, 2.02, '  Measured', fontsize=6, color='#388E3C')
    ax.set_xlabel('Acceptance Rate (%)')
    ax.set_ylabel('Speedup (×)')
    ax.set_title('(e) Speedup vs Accept Rate')

    # ---- (f) Summary Box ----
    ax = fig.add_subplot(gs[1, 2])
    ax.axis('off')
    summary = (
        "══════ RESULTS ══════\n\n"
        "Model: GPT-2 124M\n"
        "Hardware: A100 40GB\n"
        "Grad Accum: 16×4 = 64\n\n"
        f"LST:      1,483.5s\n"
        f"Baseline: 2,997.4s\n"
        f"Speedup:  2.02×\n\n"
        f"LST Loss:      6.29\n"
        f"Baseline Loss: 5.59\n"
        f"Accept Rate:   76.3%\n"
        f"Draft Params:  ~3M\n"
    )
    ax.text(0.05, 0.95, summary, transform=ax.transAxes, fontsize=7.5,
            va='top', fontfamily='monospace',
            bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.9, edgecolor='black'))
    ax.set_title('(f) Summary')

    fig.savefig(os.path.join(OUT_DIR, 'fig_combined.pdf'))
    fig.savefig(os.path.join(OUT_DIR, 'fig_combined.png'))
    plt.close(fig)
    print("Generated fig_combined")


# ====================================================================
#  Main
# ====================================================================
if __name__ == '__main__':
    import sys

    # Try to load checkpoints
    lst_path = 'lst_checkpoint.pkl'
    base_path = 'baseline_checkpoint.pkl'

    # Check common locations
    for prefix in ['.', 'notebooks', '..']:
        lp = os.path.join(prefix, lst_path)
        bp = os.path.join(prefix, base_path)
        if os.path.exists(lp) and os.path.exists(bp):
            lst_path, base_path = lp, bp
            break

    # Generate figures that don't need data
    fig1_architecture()
    fig5_cost_model()
    fig6_speedup_vs_acceptance()

    # Generate figures that need checkpoint data
    if os.path.exists(lst_path) and os.path.exists(base_path):
        print(f"\nLoading checkpoints: {lst_path}, {base_path}")
        lst, base = load_checkpoints(lst_path, base_path)
        fig2_loss_curves(lst, base)
        fig3_acceptance_rate(lst)
        fig4_step_time_distribution(lst, base)
        fig_combined(lst, base)
    else:
        print(f"\nCheckpoint files not found ({lst_path}, {base_path}).")
        print("Generating synthetic data for figure layout preview...")

        # Synthetic data for layout preview
        np.random.seed(42)
        n = 2000
        lst_synthetic = {
            'losses': 10 - 3.5 * (1 - np.exp(-np.arange(n)/500)) + np.random.randn(n)*0.3,
            'step_times': np.where(np.arange(n) < 50, 1.341, np.where(np.random.rand(n) < 0.76, 0.156, 1.4)) + np.random.randn(n)*0.02,
            'accepted_flags': (np.random.rand(n-50) < np.linspace(1.0, 0.76, n-50)).astype(float).tolist(),
            'acceptance_rates': np.linspace(1.0, 0.763, n).tolist(),
            'draft_losses': (0.1 * np.exp(-np.arange(n)/300) + np.random.randn(n)*0.005).tolist(),
            'tolerances': np.maximum(0.005, 0.015 * 0.95**(np.arange(n)/20)).tolist(),
            'steps_done': n,
            'total_time': 1483.5,
            'lst_total_accepted': 1413,
            'lst_total_speculative': 1852,
            'lst_final_tolerance': 0.005,
            'lst_draft_params': 3000000,
        }
        base_synthetic = {
            'baseline_losses': 10 - 4.0 * (1 - np.exp(-np.arange(n)/500)) + np.random.randn(n)*0.3,
            'baseline_times': (1.226 + np.random.randn(n)*0.02).tolist(),
            'baseline_steps': n,
            'baseline_total_time': 2997.4,
        }

        fig2_loss_curves(lst_synthetic, base_synthetic)
        fig3_acceptance_rate(lst_synthetic)
        fig4_step_time_distribution(lst_synthetic, base_synthetic)
        fig_combined(lst_synthetic, base_synthetic)
        print("\n[NOTE] Figures generated with SYNTHETIC data for layout preview.")
        print("Re-run after training to get real figures.")

    print(f"\nAll figures saved to: {OUT_DIR}/")
